name: "SkyFolia"
version: "${version}"
main: fr.euphyllia.skyfolia.Main
api-version: 1.20
author: Euphyllia
description: "${description}"
folia-supported: true
depend:
  - WorldEdit

commands:
  skyfolia:
    description: "Plugin Island"
    aliases:
      - island
      - is